### ISSUE TITLE
Not parsing multi-line arrays properly

### ISSUE THREAD

**Issue by TensorTom** [TiePy/nimatron#1] opened 2020-07-29 21:06 UTC
Multi-line arrays produce an error:

![multiline array error](https://i.imgur.com/y3AKfVw.png)

**Comment by stever** [comment] 2020-07-29 21:09
@TensorTom Thanks for the issue report. I'll get a fix for this into the next release. I'll let you know when it's fixed and submitted.

**Closed** 2020-07-29 21:50 UTC

**Comment by stever** [comment] 2020-07-29 21:56
Correction to grammar has been made to fix this. Related to optional indentation. A new build will be submitted to the plugin repository. I'm not sure of compatibility though. I've just updated a few JetBrains IDEs and it seems the default plugin version range is very narrow. So, it may require the new 2020.2 version of CLion.

**Comment by stever** [comment] 2020-07-29 22:08
Version 1.1.1 has now been submitted to the plugin repository for moderation.

**Comment by stever** [comment] 2020-07-30 10:01
> Version 1.1.1 of the Nimatron plugin has been approved by JetBrains and is now publicly available by the following link: https://plugins.jetbrains.com/plugin/14520-nimatron/versions/stable/93267.

As noted before, this update is for the latest 2020.2 versions. I'm still investigating how to improve version compatibility.

**Comment by RecruitMain707** [comment] 2020-08-24 10:17
This is still an issue when there are more than 1 items per row:
![image](https://user-images.githubusercontent.com/37117366/91033497-be498100-e603-11ea-9426-f4bcaf7c415f.png)

The error message: `NimTokenType.DEDENT or NimTokenType.IND_EQ expected, got 'cp'`

**Comment by stever** [comment] 2020-08-24 11:15
New version of the plugin was submitted late last night. I don't think it's available yet. Your example here is very different to the original issue, which was resolved. I'd create a new issue if this is a new problem to consider.

**Comment by stever** [comment] 2020-08-24 11:28
@RecruitMain707 Thinking about this a bit more, this may still be the case. It's a frustrating limitation of the JFlex/Grammar-Kit provided by the IDEA platform. I'm investigating how Nim indent handling can be done. Currently it would be impossible to do this following the way a parser is contructed for the IntelliJ-platform. I might be able to hack a workaround (I've got an idea how I might do it). The problem is lexer tokens don't have any info returned to the parser. Nim ignore indent levels a lot of the time. They use hand-written lexer and parser which treats indents in a way that I haven't got a certain solution for currently. I would link this to the Nim indents "known issue" that I've mentioned in the repository README here.

**Comment by stever** [comment] 2020-08-25 20:44
Previous commit meant to refer to issue #11. General solution for indent handling in nested comments.
