### ISSUE TITLE
marking a number as float/int/etc with a comma is not highlighted properly

### ISSUE THREAD

**Issue by RecruitMain707** [TiePy/nimatron#3] opened 2020-08-12 19:08 UTC
i think it is a rather trivial error and it should be easy to solve, but currently, when you try to set a number's type with an 
apostrophe, (for example: `var i = 1'f`), its not recognized as a number, and its highlighted as an string.

**Comment by stever** [comment] 2020-08-13 12:42
Plugin version 1.2.1 has been submitted for moderation.

**Comment by stever** [comment] 2020-08-13 14:59
Updated plugin is now available.

**Comment by stever** [comment] 2020-08-15 13:23
Quoting comment from issue #4 which relates to this issue. 

> Also, regarding the last fix you did about assigning number types with an apostrophe, you forgot to add the other possiblities, (i32, i16, i8, f32, etc...)
> 
> the full list is here:
> https://nim-lang.org/docs/manual.html#lexical-analysis-numerical-constants
> (scroll a bit down and you will find a table with all of them)

When I looked at this issue I found that the `1'f` wasn't recognised correctly because I had not read the Nim grammar you referenced as intended with respect to the optional `32` suffix. So that's what I've corrected previously.

Having another look at this I can see another couple of problems. One is that the manual also provides `d|D` suffix for 64-bit floats. So I'm adding that. The other is related to a series of var statements being gobbled together as one by the first line. Some of the grammar rules are a bit peculiar - but this is a separate issue.

I couldn't find any further problems with the other possibilities. I've extended the test case in the last commit, noted above. Is there some other tests here that I've missed that are still not highlighted correctly?

**Comment by RecruitMain707** [comment] 2020-08-15 18:48
not that i know of

**Comment by stever** [comment] 2020-08-16 13:33
I've modified the lexer rules to ignore newlines in parenthesis instead of the grammar modification. I've also resolved the issue with var statements together. There is a lookahead predicate that seems to be supported which helps with the greedy rule. I believe this issue is resolved for the next plugin release, so closing this again for now.

**Closed by stever** 2020-08-16 13:33 UTC
Labels: bug
