### ISSUE TITLE
Multiple objects defined in the same type block is marked as an error

### ISSUE THREAD

**Issue by RecruitMain707** [TiePy/nimatron#2] opened 2020-08-01 16:50 UTC
Fisrt of all, thank you for creating this plugin, it looks very promising, thats why id like to help reporting the possible errors i might find (let me know if you want me to do it over here at github, somewhere else, or just not do it).

After that unnecesary introduction...

this code right here:
```nim
type       # the error appears in this "=" symbol
  Offsets = tuple[lPlayer: ByteAddress, fJump: ByteAddress, flags: ByteAddress]
  Values = tuple[localPlayer: ByteAddress, gameModule: ByteAddress, flag: byte]
```

shows this error:
```
',', '.', <op>, <primary suffix>, NimTokenType.COMMENT, NimTokenType.DEDENT, NimTokenType.IND_EQ or '{.' expected, got '='
```

**Comment by stever** [comment] 2020-08-01 17:11
Thank-you for the bug report. I am happy to resolve issues here.

It was quite a lot of effort to get so far with the parser. It is not a simple copy & paste from the language specification by any means, and I expect there will be a few cases to resolve, like this one. I'll let you know when it is fixed. I will take a look later today, and try to fix it before the end of the weekend.

**Comment by stever** [comment] 2020-08-02 21:14
This is quite an interesting example. The grammar specified for the language is more informal than I first thought it would be. Seems to be compiled from comments in the parser code, which is then not entirely accurate it seems. I'll probably just get more familiar with the Nim parser to work out some of the rules required here.

I'll work on it over the next week, as time allows. Note that this will take more time, but I'll get to the bottom of it.

**Comment by RecruitMain707** [comment] 2020-08-03 11:48
you could also check [nimsuggest](https://nim-lang.org/docs/nimsuggest.html) and [idetools](https://nim-lang.org/docs/idetools.html) now that the plugin is rather new, it could save you some time maybe, i dont know how intellij really works though

**Comment by stever** [comment] 2020-08-03 12:18
These would be useful. Integration with these could be done by configuration. I will look into that once I get the grammar updated. There's a few wrinkles here to work out, and then I would like to get auto-indent working too.

**Comment by stever** [comment] 2020-08-09 22:06
I found that some of the parser rules were over-greedy and as a result some of the rules were not being used correctly. I have re-worked the grammar in a few ways, resolving this issue and other potential issues too. Thanks for bringing this to my attention @RecruitMain707.

**Closed by stever** 2020-08-09 22:06 UTC
Labels: bug

**Comment by stever** [comment] 2020-08-09 22:08
I should add that version 1.2.0 of the plugin has been submitted to the JetBrains Plugin Repository. It may take a couple of days for the update to go live.

**Comment by stever** [comment] 2020-08-10 12:53
The updated plugin is now confirmed & available.

**Comment by RecruitMain707** [comment] 2020-08-11 15:36
cool!
keep it up man :)
